<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KenyanBankBranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Get all banks to map bank_code to bank_id
        $banks = DB::table('banks')->pluck('id', 'bank_code');

        $locations = [
            ['bank_code' => '01', 'branch_code' => '231', 'branch_name' => 'Kapsowar'],
            ['bank_code' => '01', 'branch_code' => '302', 'branch_name' => 'Diaspora'],
            ['bank_code' => '01', 'branch_code' => '303', 'branch_name' => 'Kisii West'],
            ['bank_code' => '01', 'branch_code' => '304', 'branch_name' => 'Mbita'],
            ['bank_code' => '01', 'branch_code' => '305', 'branch_name' => 'Sori'],
            ['bank_code' => '01', 'branch_code' => '306', 'branch_name' => 'Hurlingham'],
            ['bank_code' => '01', 'branch_code' => '307', 'branch_name' => 'Kibera'],
            ['bank_code' => '01', 'branch_code' => '308', 'branch_name' => 'Thika Road Mall Location'],
            ['bank_code' => '01', 'branch_code' => '309', 'branch_name' => 'Kasarani Location'],
            ['bank_code' => '01', 'branch_code' => '310', 'branch_name' => 'KCB Maasai Mara'],
            ['bank_code' => '01', 'branch_code' => '311', 'branch_name' => 'KCB Kabartonjo'],
            ['bank_code' => '01', 'branch_code' => '312', 'branch_name' => 'KCB Eldoret East'],
            ['bank_code' => '01', 'branch_code' => '313', 'branch_name' => 'Kikim'],
            ['bank_code' => '01', 'branch_code' => '314', 'branch_name' => 'KCB JKUAT'],
            ['bank_code' => '01', 'branch_code' => '315', 'branch_name' => 'KCB Changamwe'],
            ['bank_code' => '01', 'branch_code' => '316', 'branch_name' => 'KCB Makongeni'],
            ['bank_code' => '01', 'branch_code' => '317', 'branch_name' => 'KCB Syokimau'],
            ['bank_code' => '01', 'branch_code' => '340', 'branch_name' => 'Karen Waterfront Platinum'],
            ['bank_code' => '01', 'branch_code' => '341', 'branch_name' => 'KCB Ngong Location'],
            ['bank_code' => '01', 'branch_code' => '325', 'branch_name' => 'Garden City'],
            ['bank_code' => '01', 'branch_code' => '326', 'branch_name' => 'JKIA'],
            ['bank_code' => '01', 'branch_code' => '327', 'branch_name' => 'Makutano'],
            ['bank_code' => '01', 'branch_code' => '330', 'branch_name' => 'KCB NextGen'],
            ['bank_code' => '01', 'branch_code' => '331', 'branch_name' => 'KCB Mogotio'],
            ['bank_code' => '01', 'branch_code' => '329', 'branch_name' => 'Two Rivers'],
            ['bank_code' => '01', 'branch_code' => '332', 'branch_name' => 'KCB Upperhill Platinum'],
            ['bank_code' => '01', 'branch_code' => '337', 'branch_name' => 'KCB Kilimani Platinum'],
            ['bank_code' => '01', 'branch_code' => '339', 'branch_name' => 'KCB Utawala'],
            ['bank_code' => '01', 'branch_code' => '242', 'branch_name' => 'Ugunja'],
            ['bank_code' => '01', 'branch_code' => '243', 'branch_name' => 'United Mall'],
            ['bank_code' => '01', 'branch_code' => '244', 'branch_name' => 'Serem'],
            ['bank_code' => '01', 'branch_code' => '245', 'branch_name' => 'Sondu'],
            ['bank_code' => '01', 'branch_code' => '246', 'branch_name' => 'Kisumu West'],
            ['bank_code' => '01', 'branch_code' => '247', 'branch_name' => 'Marigat'],
            ['bank_code' => '01', 'branch_code' => '248', 'branch_name' => 'Mois Bridge'],
            ['bank_code' => '01', 'branch_code' => '249', 'branch_name' => 'Mashariki'],
            ['bank_code' => '01', 'branch_code' => '250', 'branch_name' => 'Naro Moro'],
            ['bank_code' => '01', 'branch_code' => '251', 'branch_name' => 'Kiriaini'],
            ['bank_code' => '01', 'branch_code' => '252', 'branch_name' => 'Egerton University'],
            ['bank_code' => '01', 'branch_code' => '253', 'branch_name' => 'Maua'],
            ['bank_code' => '01', 'branch_code' => '254', 'branch_name' => 'Kawangare'],
            ['bank_code' => '01', 'branch_code' => '255', 'branch_name' => 'Kimathi'],
            ['bank_code' => '01', 'branch_code' => '256', 'branch_name' => 'Namanga'],
            ['bank_code' => '01', 'branch_code' => '288', 'branch_name' => 'Haile Selassie'],
            ['bank_code' => '01', 'branch_code' => '289', 'branch_name' => 'Salama House Mortgage Centre'],
            ['bank_code' => '01', 'branch_code' => '290', 'branch_name' => 'Garden Plaza'],
            ['bank_code' => '01', 'branch_code' => '291', 'branch_name' => 'Sarit Centre Mortgage Centre'],
            ['bank_code' => '01', 'branch_code' => '292', 'branch_name' => 'Cpc Bulk Corporate Cheques'],
            ['bank_code' => '01', 'branch_code' => '293', 'branch_name' => 'Trade Services'],
            ['bank_code' => '01', 'branch_code' => '295', 'branch_name' => 'Nairobi High Court'],
            ['bank_code' => '01', 'branch_code' => '296', 'branch_name' => 'Mombasa High Court'],
            ['bank_code' => '01', 'branch_code' => '297', 'branch_name' => 'Kisumu Airport'],
            ['bank_code' => '01', 'branch_code' => '298', 'branch_name' => 'Port Victoria'],
            ['bank_code' => '01', 'branch_code' => '300', 'branch_name' => 'Nyali'],
            ['bank_code' => '01', 'branch_code' => '301', 'branch_name' => 'Westgate Advantage'],
            ['bank_code' => '01', 'branch_code' => '287', 'branch_name' => 'Kisauni'],
            ['bank_code' => '01', 'branch_code' => '257', 'branch_name' => 'Gikomba'],
            ['bank_code' => '01', 'branch_code' => '258', 'branch_name' => 'Kwale'],
            ['bank_code' => '01', 'branch_code' => '259', 'branch_name' => 'Prestige Plaza'],
            ['bank_code' => '01', 'branch_code' => '260', 'branch_name' => 'Kariobangi'],
            ['bank_code' => '01', 'branch_code' => '263', 'branch_name' => 'Biashara Street'],
            ['bank_code' => '01', 'branch_code' => '266', 'branch_name' => 'Ngara'],
            ['bank_code' => '01', 'branch_code' => '267', 'branch_name' => 'Kyuso'],
            ['bank_code' => '01', 'branch_code' => '270', 'branch_name' => 'Masii'],
            ['bank_code' => '01', 'branch_code' => '271', 'branch_name' => 'Menengai Crater'],
            ['bank_code' => '01', 'branch_code' => '272', 'branch_name' => 'Town Centre'],
            ['bank_code' => '01', 'branch_code' => '278', 'branch_name' => 'Makindu'],
            ['bank_code' => '01', 'branch_code' => '283', 'branch_name' => 'Rongo'],
            ['bank_code' => '01', 'branch_code' => '284', 'branch_name' => 'Isibania'],
            ['bank_code' => '01', 'branch_code' => '318', 'branch_name' => 'KCB Moi Referral Hospital'],
            ['bank_code' => '01', 'branch_code' => '319', 'branch_name' => 'KCB Kitale Advantage'],
            ['bank_code' => '01', 'branch_code' => '320', 'branch_name' => 'KCB Lavington'],
            ['bank_code' => '01', 'branch_code' => '322', 'branch_name' => 'KCB Riverside Advantage'],
            ['bank_code' => '01', 'branch_code' => '323', 'branch_name' => 'KCB Gigiri Square'],
            ['bank_code' => '01', 'branch_code' => '324', 'branch_name' => 'Kayole'],
            ['bank_code' => '01', 'branch_code' => '214', 'branch_name' => 'Gatundu'],
            ['bank_code' => '01', 'branch_code' => '215', 'branch_name' => 'Emali'],
            ['bank_code' => '01', 'branch_code' => '216', 'branch_name' => 'Isiolo'],
            ['bank_code' => '01', 'branch_code' => '217', 'branch_name' => 'KCB Flamingo'],
            ['bank_code' => '01', 'branch_code' => '218', 'branch_name' => 'Njoro'],
            ['bank_code' => '01', 'branch_code' => '219', 'branch_name' => 'Mutomo'],
            ['bank_code' => '01', 'branch_code' => '220', 'branch_name' => 'Mariakani'],
            ['bank_code' => '01', 'branch_code' => '221', 'branch_name' => 'Mpeketoni'],
            ['bank_code' => '01', 'branch_code' => '222', 'branch_name' => 'Mtitu Andei'],
            ['bank_code' => '01', 'branch_code' => '223', 'branch_name' => 'Mtwapa'],
            ['bank_code' => '01', 'branch_code' => '224', 'branch_name' => 'Taveta'],
            ['bank_code' => '01', 'branch_code' => '225', 'branch_name' => 'Kengeleni'],
            ['bank_code' => '01', 'branch_code' => '226', 'branch_name' => 'Garsen'],
            ['bank_code' => '01', 'branch_code' => '227', 'branch_name' => 'Watamu'],
            ['bank_code' => '01', 'branch_code' => '228', 'branch_name' => 'Bondo'],
            ['bank_code' => '01', 'branch_code' => '229', 'branch_name' => 'Busia'],
            ['bank_code' => '01', 'branch_code' => '230', 'branch_name' => 'Homa Bay'],
            ['bank_code' => '01', 'branch_code' => '185', 'branch_name' => 'Othaya'],
            ['bank_code' => '01', 'branch_code' => '186', 'branch_name' => 'Voi'],
            ['bank_code' => '01', 'branch_code' => '188', 'branch_name' => 'Webuye'],
            ['bank_code' => '01', 'branch_code' => '163', 'branch_name' => 'Eldama Ravine'],
            ['bank_code' => '01', 'branch_code' => '164', 'branch_name' => 'Kibwezi'],
            ['bank_code' => '01', 'branch_code' => '166', 'branch_name' => 'Kapsabet'],
            ['bank_code' => '01', 'branch_code' => '167', 'branch_name' => 'University Way'],
            ['bank_code' => '01', 'branch_code' => '168', 'branch_name' => 'KCB Eldoret West'],
            ['bank_code' => '01', 'branch_code' => '169', 'branch_name' => 'Garissa'],
            ['bank_code' => '01', 'branch_code' => '124', 'branch_name' => 'Mumias'],
            ['bank_code' => '01', 'branch_code' => '125', 'branch_name' => 'Nanyuki'],
            ['bank_code' => '01', 'branch_code' => '127', 'branch_name' => 'Moyale'],
            ['bank_code' => '01', 'branch_code' => '129', 'branch_name' => 'Kikuyu'],
            ['bank_code' => '01', 'branch_code' => '130', 'branch_name' => 'Tala'],
            ['bank_code' => '01', 'branch_code' => '131', 'branch_name' => 'Kajiado'],
            ['bank_code' => '01', 'branch_code' => '133', 'branch_name' => 'KCB Custody services'],
            ['bank_code' => '01', 'branch_code' => '134', 'branch_name' => 'Matuu'],
            ['bank_code' => '01', 'branch_code' => '135', 'branch_name' => 'Kitui'],
            ['bank_code' => '01', 'branch_code' => '136', 'branch_name' => 'Mvita'],
            ['bank_code' => '01', 'branch_code' => '137', 'branch_name' => 'Jogoo Rd Nairobi'],
            ['bank_code' => '01', 'branch_code' => '139', 'branch_name' => 'Card Centre'],
            ['bank_code' => '01', 'branch_code' => '140', 'branch_name' => 'Marsabit'],
            ['bank_code' => '01', 'branch_code' => '141', 'branch_name' => 'Sarit Centre'],
            ['bank_code' => '01', 'branch_code' => '142', 'branch_name' => 'Loitokitok'],
            ['bank_code' => '01', 'branch_code' => '143', 'branch_name' => 'Nandi Hills'],
            ['bank_code' => '01', 'branch_code' => '144', 'branch_name' => 'Lodwar'],
            ['bank_code' => '01', 'branch_code' => '145', 'branch_name' => 'Un Gigiri'],
            ['bank_code' => '01', 'branch_code' => '146', 'branch_name' => 'Hola'],
            ['bank_code' => '01', 'branch_code' => '147', 'branch_name' => 'Ruiru'],
            ['bank_code' => '01', 'branch_code' => '148', 'branch_name' => 'Mwingi'],
            ['bank_code' => '01', 'branch_code' => '149', 'branch_name' => 'Kitale'],
            ['bank_code' => '01', 'branch_code' => '150', 'branch_name' => 'Mandera'],
            ['bank_code' => '01', 'branch_code' => '151', 'branch_name' => 'Kapenguria'],
            ['bank_code' => '01', 'branch_code' => '152', 'branch_name' => 'Kabarnet'],
            ['bank_code' => '01', 'branch_code' => '153', 'branch_name' => 'Wajir'],
            ['bank_code' => '01', 'branch_code' => '154', 'branch_name' => 'Maralal'],
            ['bank_code' => '01', 'branch_code' => '155', 'branch_name' => 'Limuru'],
            ['bank_code' => '01', 'branch_code' => '157', 'branch_name' => 'Ukunda'],
            ['bank_code' => '01', 'branch_code' => '158', 'branch_name' => 'Iten'],
            ['bank_code' => '01', 'branch_code' => '159', 'branch_name' => 'Gilgil'],
            ['bank_code' => '01', 'branch_code' => '161', 'branch_name' => 'Ongata Rongai'],
            ['bank_code' => '01', 'branch_code' => '162', 'branch_name' => 'Kitengela'],
            ['bank_code' => '01', 'branch_code' => '345', 'branch_name' => 'KCB Mokowe'],
            ['bank_code' => '01', 'branch_code' => '346', 'branch_name' => 'KCB Kendu Bay'],
            ['bank_code' => '01', 'branch_code' => '355', 'branch_name' => 'KCB SAHL Centre Eastleign Location'],
            ['bank_code' => '01', 'branch_code' => '347', 'branch_name' => 'KCB Greenwood Mall'],
            ['bank_code' => '01', 'branch_code' => '338', 'branch_name' => 'KCB Langata'],
            ['bank_code' => '01', 'branch_code' => '348', 'branch_name' => 'KCB Kamakis'],
            ['bank_code' => '01', 'branch_code' => '344', 'branch_name' => 'KCB Rumuruti Location'],
            ['bank_code' => '01', 'branch_code' => '091', 'branch_name' => 'Eastleigh'],
            ['bank_code' => '01', 'branch_code' => '285', 'branch_name' => 'Kiserian'],
            ['bank_code' => '01', 'branch_code' => '286', 'branch_name' => 'Mwembe Tayari'],
            ['bank_code' => '01', 'branch_code' => '342', 'branch_name' => 'Imara Daima'],
            ['bank_code' => '01', 'branch_code' => '343', 'branch_name' => 'Takaba Town'],
            ['bank_code' => '01', 'branch_code' => '232', 'branch_name' => 'Kehancha'],
            ['bank_code' => '01', 'branch_code' => '233', 'branch_name' => 'Keroka'],
            ['bank_code' => '01', 'branch_code' => '234', 'branch_name' => 'Kilgoris'],
            ['bank_code' => '01', 'branch_code' => '235', 'branch_name' => 'Kimilili'],
            ['bank_code' => '01', 'branch_code' => '236', 'branch_name' => 'Litein'],
            ['bank_code' => '01', 'branch_code' => '237', 'branch_name' => 'Londiani Location'],
            ['bank_code' => '01', 'branch_code' => '238', 'branch_name' => 'Luanda'],
            ['bank_code' => '01', 'branch_code' => '239', 'branch_name' => 'Malaba'],
            ['bank_code' => '01', 'branch_code' => '240', 'branch_name' => 'Muhoroni'],
            ['bank_code' => '01', 'branch_code' => '241', 'branch_name' => 'Oyugis'],
            ['bank_code' => '01', 'branch_code' => '189', 'branch_name' => 'Sotik'],
            ['bank_code' => '01', 'branch_code' => '190', 'branch_name' => 'Naivasha'],
            ['bank_code' => '01', 'branch_code' => '191', 'branch_name' => 'Kisii'],
            ['bank_code' => '01', 'branch_code' => '192', 'branch_name' => 'Migori'],
            ['bank_code' => '01', 'branch_code' => '193', 'branch_name' => 'Githunguri'],
            ['bank_code' => '01', 'branch_code' => '194', 'branch_name' => 'Machakos'],
            ['bank_code' => '01', 'branch_code' => '195', 'branch_name' => 'Kerugoya'],
            ['bank_code' => '01', 'branch_code' => '196', 'branch_name' => 'Chuka'],
            ['bank_code' => '01', 'branch_code' => '197', 'branch_name' => 'Bungoma'],
            ['bank_code' => '01', 'branch_code' => '198', 'branch_name' => 'Wundanyi'],
            ['bank_code' => '01', 'branch_code' => '199', 'branch_name' => 'Malindi'],
            ['bank_code' => '01', 'branch_code' => '201', 'branch_name' => 'Capital Hill'],
            ['bank_code' => '01', 'branch_code' => '202', 'branch_name' => 'Karen'],
            ['bank_code' => '01', 'branch_code' => '203', 'branch_name' => 'Lokichogio'],
            ['bank_code' => '01', 'branch_code' => '204', 'branch_name' => 'Gateway Msa Road'],
            ['bank_code' => '01', 'branch_code' => '205', 'branch_name' => 'Buruburu'],
            ['bank_code' => '01', 'branch_code' => '206', 'branch_name' => 'Chogoria'],
            ['bank_code' => '01', 'branch_code' => '207', 'branch_name' => 'Kangare'],
            ['bank_code' => '01', 'branch_code' => '208', 'branch_name' => 'Kianyaga'],
            ['bank_code' => '01', 'branch_code' => '209', 'branch_name' => 'Nkubu'],
            ['bank_code' => '01', 'branch_code' => '210', 'branch_name' => 'Ol Kalou'],
            ['bank_code' => '01', 'branch_code' => '211', 'branch_name' => 'Makuyu'],
            ['bank_code' => '01', 'branch_code' => '212', 'branch_name' => 'Mwea'],
            ['bank_code' => '01', 'branch_code' => '213', 'branch_name' => 'Njambini'],
            ['bank_code' => '01', 'branch_code' => '333', 'branch_name' => 'Kakuma Location'],
            ['bank_code' => '01', 'branch_code' => '334', 'branch_name' => 'KCB Parklands'],
            ['bank_code' => '01', 'branch_code' => '335', 'branch_name' => 'KCB Diani'],
            ['bank_code' => '01', 'branch_code' => '336', 'branch_name' => 'KCB Eldoret Advantage Location'],
            ['bank_code' => '01', 'branch_code' => '092', 'branch_name' => 'KCB CPC'],
            ['bank_code' => '01', 'branch_code' => '094', 'branch_name' => 'Head Office'],
            ['bank_code' => '01', 'branch_code' => '095', 'branch_name' => 'Wote'],
            ['bank_code' => '01', 'branch_code' => '096', 'branch_name' => 'Head Office Finance'],
            ['bank_code' => '01', 'branch_code' => '100', 'branch_name' => 'Moi Avenue Nairobi'],
            ['bank_code' => '01', 'branch_code' => '101', 'branch_name' => 'Kipande House'],
            ['bank_code' => '01', 'branch_code' => '102', 'branch_name' => 'Treasury Sq Mombasa'],
            ['bank_code' => '01', 'branch_code' => '103', 'branch_name' => 'Nakuru'],
            ['bank_code' => '01', 'branch_code' => '104', 'branch_name' => 'Kicc'],
            ['bank_code' => '01', 'branch_code' => '105', 'branch_name' => 'Kisumu'],
            ['bank_code' => '01', 'branch_code' => '106', 'branch_name' => 'Kericho'],
            ['bank_code' => '01', 'branch_code' => '107', 'branch_name' => 'Tom Mboya'],
            ['bank_code' => '01', 'branch_code' => '108', 'branch_name' => 'Thika'],
            ['bank_code' => '01', 'branch_code' => '109', 'branch_name' => 'Eldoret'],
            ['bank_code' => '01', 'branch_code' => '110', 'branch_name' => 'Kakamega'],
            ['bank_code' => '01', 'branch_code' => '111', 'branch_name' => 'Kilindini Mombasa'],
            ['bank_code' => '01', 'branch_code' => '112', 'branch_name' => 'Nyeri'],
            ['bank_code' => '01', 'branch_code' => '113', 'branch_name' => 'Industrial Area Nairobi'],
            ['bank_code' => '01', 'branch_code' => '114', 'branch_name' => 'River Road'],
            ['bank_code' => '01', 'branch_code' => '115', 'branch_name' => 'Muranga'],
            ['bank_code' => '01', 'branch_code' => '116', 'branch_name' => 'Embu'],
            ['bank_code' => '01', 'branch_code' => '117', 'branch_name' => 'Kangema'],
            ['bank_code' => '01', 'branch_code' => '119', 'branch_name' => 'Kiambu'],
            ['bank_code' => '01', 'branch_code' => '120', 'branch_name' => 'Karatina'],
            ['bank_code' => '01', 'branch_code' => '121', 'branch_name' => 'Siaya'],
            ['bank_code' => '01', 'branch_code' => '122', 'branch_name' => 'Nyahururu'],
            ['bank_code' => '01', 'branch_code' => '123', 'branch_name' => 'Meru'],
            ['bank_code' => '01', 'branch_code' => '173', 'branch_name' => 'Lamu'],
            ['bank_code' => '01', 'branch_code' => '174', 'branch_name' => 'Kilifi'],
            ['bank_code' => '01', 'branch_code' => '175', 'branch_name' => 'Milimani'],
            ['bank_code' => '01', 'branch_code' => '176', 'branch_name' => 'Nyamira'],
            ['bank_code' => '01', 'branch_code' => '177', 'branch_name' => 'Mukuruweini'],
            ['bank_code' => '01', 'branch_code' => '180', 'branch_name' => 'Village Market'],
            ['bank_code' => '01', 'branch_code' => '181', 'branch_name' => 'Bomet'],
            ['bank_code' => '01', 'branch_code' => '183', 'branch_name' => 'Mbale'],
            ['bank_code' => '01', 'branch_code' => '184', 'branch_name' => 'Narok'],
            ['bank_code' => '02', 'branch_code' => '090', 'branch_name' => 'Bungoma'],
            ['bank_code' => '02', 'branch_code' => '091', 'branch_name' => 'Thika Road Mall'],
            ['bank_code' => '02', 'branch_code' => '092', 'branch_name' => 'UN Gigiri'],
            ['bank_code' => '02', 'branch_code' => '000', 'branch_name' => 'Eldoret'],
            ['bank_code' => '02', 'branch_code' => '001', 'branch_name' => 'Kericho'],
            ['bank_code' => '02', 'branch_code' => '002', 'branch_name' => 'Kisumu'],
            ['bank_code' => '02', 'branch_code' => '003', 'branch_name' => 'Kitale'],
            ['bank_code' => '02', 'branch_code' => '004', 'branch_name' => 'Treasury Square'],
            ['bank_code' => '02', 'branch_code' => '005', 'branch_name' => 'Kilindini'],
            ['bank_code' => '02', 'branch_code' => '006', 'branch_name' => 'Kenyatta Avenue'],
            ['bank_code' => '02', 'branch_code' => '008', 'branch_name' => 'Moi Avenue'],
            ['bank_code' => '02', 'branch_code' => '009', 'branch_name' => 'Nakuru'],
            ['bank_code' => '02', 'branch_code' => '010', 'branch_name' => 'Nanyuki'],
            ['bank_code' => '02', 'branch_code' => '011', 'branch_name' => 'Nyeri'],
            ['bank_code' => '02', 'branch_code' => '012', 'branch_name' => 'Thika'],
            ['bank_code' => '02', 'branch_code' => '015', 'branch_name' => 'Westlands'],
            ['bank_code' => '02', 'branch_code' => '016', 'branch_name' => 'Machakos'],
            ['bank_code' => '02', 'branch_code' => '017', 'branch_name' => 'Meru'],
            ['bank_code' => '02', 'branch_code' => '019', 'branch_name' => 'Harambee Avenue'],
            ['bank_code' => '02', 'branch_code' => '053', 'branch_name' => 'Industrial Area'],
            ['bank_code' => '02', 'branch_code' => '054', 'branch_name' => 'Kakamega'],
            ['bank_code' => '02', 'branch_code' => '064', 'branch_name' => 'Koinage'],
            ['bank_code' => '02', 'branch_code' => '071', 'branch_name' => 'Yaya Centre Location'],
            ['bank_code' => '02', 'branch_code' => '072', 'branch_name' => 'Ruaraka'],
            ['bank_code' => '02', 'branch_code' => '073', 'branch_name' => 'Langata'],
            ['bank_code' => '02', 'branch_code' => '074', 'branch_name' => 'Makupa'],
            ['bank_code' => '02', 'branch_code' => '75', 'branch_name' => 'Karen'],
            ['bank_code' => '02', 'branch_code' => '076', 'branch_name' => 'Muthaiga'],
            ['bank_code' => '02', 'branch_code' => '078', 'branch_name' => 'C.o.u'],
            ['bank_code' => '02', 'branch_code' => '079', 'branch_name' => 'Ukay'],
            ['bank_code' => '02', 'branch_code' => '080', 'branch_name' => 'Two Rivers Location'],
            ['bank_code' => '02', 'branch_code' => '081', 'branch_name' => 'Kisii'],
            ['bank_code' => '02', 'branch_code' => '082', 'branch_name' => 'Upper Hill Location'],
            ['bank_code' => '02', 'branch_code' => '083', 'branch_name' => 'Nyali'],
            ['bank_code' => '02', 'branch_code' => '084', 'branch_name' => 'Chiromo'],
            ['bank_code' => '02', 'branch_code' => '085', 'branch_name' => 'Greenspan'],
            ['bank_code' => '02', 'branch_code' => '086', 'branch_name' => 'The T-Mall'],
            ['bank_code' => '02', 'branch_code' => '087', 'branch_name' => 'The Junction'],
            ['bank_code' => '02', 'branch_code' => '089', 'branch_name' => 'Kitengela'],
            ['bank_code' => '03', 'branch_code' => '065', 'branch_name' => 'Karen Location'],
            ['bank_code' => '03', 'branch_code' => '066', 'branch_name' => 'Wundanyi Location'],
            ['bank_code' => '03', 'branch_code' => '067', 'branch_name' => 'Ruaraka Location'],
            ['bank_code' => '03', 'branch_code' => '068', 'branch_name' => 'Kitengela Location'],
            ['bank_code' => '03', 'branch_code' => '069', 'branch_name' => 'Wote Location'],
            ['bank_code' => '03', 'branch_code' => '070', 'branch_name' => 'Enterprise Road Location'],
            ['bank_code' => '03', 'branch_code' => '071', 'branch_name' => 'Nakumatt Meru Location'],
            ['bank_code' => '03', 'branch_code' => '072', 'branch_name' => 'Juja Location'],
            ['bank_code' => '03', 'branch_code' => '073', 'branch_name' => 'Westlands Location'],
            ['bank_code' => '03', 'branch_code' => '074', 'branch_name' => 'Kikuyu Location'],
            ['bank_code' => '03', 'branch_code' => '075', 'branch_name' => 'Moi Avenue-nairobi Location'],
            ['bank_code' => '03', 'branch_code' => '076', 'branch_name' => 'Nyali'],
            ['bank_code' => '03', 'branch_code' => '077', 'branch_name' => 'Absa Towers Location'],
            ['bank_code' => '03', 'branch_code' => '034', 'branch_name' => 'Kawangware'],
            ['bank_code' => '03', 'branch_code' => '035', 'branch_name' => 'Mbale'],
            ['bank_code' => '03', 'branch_code' => '036', 'branch_name' => 'Plaza Premier Centre'],
            ['bank_code' => '03', 'branch_code' => '037', 'branch_name' => 'River Road Location'],
            ['bank_code' => '03', 'branch_code' => '038', 'branch_name' => 'Chomba House-river Road'],
            ['bank_code' => '03', 'branch_code' => '039', 'branch_name' => 'Mumias Location'],
            ['bank_code' => '03', 'branch_code' => '040', 'branch_name' => 'Machakos Location'],
            ['bank_code' => '03', 'branch_code' => '041', 'branch_name' => 'Narok Location'],
            ['bank_code' => '03', 'branch_code' => '042', 'branch_name' => 'Isiolo Location'],
            ['bank_code' => '03', 'branch_code' => '043', 'branch_name' => 'Ngong Location'],
            ['bank_code' => '03', 'branch_code' => '044', 'branch_name' => 'Maua Location'],
            ['bank_code' => '03', 'branch_code' => '045', 'branch_name' => 'Hurlingham Location'],
            ['bank_code' => '03', 'branch_code' => '046', 'branch_name' => 'Makupa Location'],
            ['bank_code' => '03', 'branch_code' => '047', 'branch_name' => 'Development House Location'],
            ['bank_code' => '03', 'branch_code' => '048', 'branch_name' => 'Bungoma'],
            ['bank_code' => '03', 'branch_code' => '027', 'branch_name' => 'Nakuru East'],
            ['bank_code' => '03', 'branch_code' => '028', 'branch_name' => 'Buruburu'],
            ['bank_code' => '03', 'branch_code' => '029', 'branch_name' => 'Bomet'],
            ['bank_code' => '03', 'branch_code' => '030', 'branch_name' => 'Nyeri Location'],
            ['bank_code' => '03', 'branch_code' => '031', 'branch_name' => 'Thika Location'],
            ['bank_code' => '03', 'branch_code' => '032', 'branch_name' => 'Port Mombasa'],
            ['bank_code' => '03', 'branch_code' => '033', 'branch_name' => 'Gikomba'],
            ['bank_code' => '03', 'branch_code' => '001', 'branch_name' => 'Head Office - Vpc'],
            ['bank_code' => '03', 'branch_code' => '002', 'branch_name' => 'Kapsabet Location'],
            ['bank_code' => '03', 'branch_code' => '003', 'branch_name' => 'Eldoret Location'],
            ['bank_code' => '03', 'branch_code' => '004', 'branch_name' => 'Embu Location'],
            ['bank_code' => '03', 'branch_code' => '005', 'branch_name' => 'Murang A Location'],
            ['bank_code' => '03', 'branch_code' => '006', 'branch_name' => 'Kapenguria Location'],
            ['bank_code' => '03', 'branch_code' => '021', 'branch_name' => 'Barclaycard Operations'],
            ['bank_code' => '03', 'branch_code' => '022', 'branch_name' => 'Paymants And International Services'],
            ['bank_code' => '03', 'branch_code' => '023', 'branch_name' => 'Gilgil Location'],
            ['bank_code' => '03', 'branch_code' => '024', 'branch_name' => 'Thika Road Mall'],
            ['bank_code' => '03', 'branch_code' => '018', 'branch_name' => 'Nyamira Location'],
            ['bank_code' => '03', 'branch_code' => '019', 'branch_name' => 'Kilifi Location'],
            ['bank_code' => '03', 'branch_code' => '020', 'branch_name' => 'Office Park Westlands'],
            ['bank_code' => '03', 'branch_code' => '026', 'branch_name' => 'Kakamega Location'],
            ['bank_code' => '03', 'branch_code' => '007', 'branch_name' => 'Kericho Location'],
            ['bank_code' => '03', 'branch_code' => '008', 'branch_name' => 'Kisii Location'],
            ['bank_code' => '03', 'branch_code' => '009', 'branch_name' => 'Kisumu Location'],
            ['bank_code' => '03', 'branch_code' => '010', 'branch_name' => 'South C Location'],
            ['bank_code' => '03', 'branch_code' => '011', 'branch_name' => 'Limuru Location'],
            ['bank_code' => '03', 'branch_code' => '012', 'branch_name' => 'Malindi Location'],
            ['bank_code' => '03', 'branch_code' => '013', 'branch_name' => 'Meru Location'],
            ['bank_code' => '03', 'branch_code' => '014', 'branch_name' => 'Eastleigh Location'],
            ['bank_code' => '03', 'branch_code' => '15', 'branch_name' => 'Kitui Location'],
            ['bank_code' => '03', 'branch_code' => '016', 'branch_name' => 'Nkrumah Road Location'],
            ['bank_code' => '03', 'branch_code' => '017', 'branch_name' => 'Garissa Location'],
            ['bank_code' => '03', 'branch_code' => '140', 'branch_name' => 'Two Rivers'],
            ['bank_code' => '03', 'branch_code' => '103', 'branch_name' => 'Nairobi J.k.i.a Location'],
            ['bank_code' => '03', 'branch_code' => '105', 'branch_name' => 'Village Market - Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '150', 'branch_name' => 'Absa Rupa Mall'],
            ['bank_code' => '03', 'branch_code' => '106', 'branch_name' => 'Sarit Centre - Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '109', 'branch_name' => 'Yaya Centre- Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '111', 'branch_name' => 'Naivasha Location'],
            ['bank_code' => '03', 'branch_code' => '113', 'branch_name' => 'Market Location'],
            ['bank_code' => '03', 'branch_code' => '114', 'branch_name' => 'Changamwe Location'],
            ['bank_code' => '03', 'branch_code' => '117', 'branch_name' => 'Rahimtulla Trust Towers - Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '125', 'branch_name' => 'Nakuru West Location'],
            ['bank_code' => '03', 'branch_code' => '078', 'branch_name' => 'Kiriaini Location'],
            ['bank_code' => '03', 'branch_code' => '079', 'branch_name' => 'Butere Road Location'],
            ['bank_code' => '03', 'branch_code' => '080', 'branch_name' => 'Migoli Location'],
            ['bank_code' => '03', 'branch_code' => '081', 'branch_name' => 'Digo Location'],
            ['bank_code' => '03', 'branch_code' => '082', 'branch_name' => 'Haile Selassie Avenue Location'],
            ['bank_code' => '03', 'branch_code' => '083', 'branch_name' => 'Nairobi University Location'],
            ['bank_code' => '03', 'branch_code' => '084', 'branch_name' => 'Bunyala Road'],
            ['bank_code' => '03', 'branch_code' => '086', 'branch_name' => 'Nairobi West Location'],
            ['bank_code' => '03', 'branch_code' => '087', 'branch_name' => 'Parklands'],
            ['bank_code' => '03', 'branch_code' => '088', 'branch_name' => 'Busia'],
            ['bank_code' => '03', 'branch_code' => '089', 'branch_name' => 'Pangani Location'],
            ['bank_code' => '03', 'branch_code' => '090', 'branch_name' => 'Abc Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '093', 'branch_name' => 'Kariobangi Location'],
            ['bank_code' => '03', 'branch_code' => '094', 'branch_name' => 'Queensway House Location'],
            ['bank_code' => '03', 'branch_code' => '095', 'branch_name' => 'Nakumatt Embakasi Location'],
            ['bank_code' => '03', 'branch_code' => '096', 'branch_name' => 'Barclays Merchant Finance Ltd.'],
            ['bank_code' => '03', 'branch_code' => '097', 'branch_name' => 'Barclays Securities Services (k'],
            ['bank_code' => '03', 'branch_code' => '100', 'branch_name' => 'Diani Location'],
            ['bank_code' => '03', 'branch_code' => '154', 'branch_name' => 'Kamakis'],
            ['bank_code' => '03', 'branch_code' => '190', 'branch_name' => 'Nanyuki Location'],
            ['bank_code' => '03', 'branch_code' => '206', 'branch_name' => 'Karatina Location'],
            ['bank_code' => '03', 'branch_code' => '220', 'branch_name' => 'Mombasa Nyerere Ave - Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '273', 'branch_name' => 'Consumer Operations'],
            ['bank_code' => '03', 'branch_code' => '300', 'branch_name' => 'Finance Department'],
            ['bank_code' => '03', 'branch_code' => '337', 'branch_name' => 'Documents And Securities Dsc'],
            ['bank_code' => '03', 'branch_code' => '152', 'branch_name' => 'Absa Imaara Mall'],
            ['bank_code' => '03', 'branch_code' => '340', 'branch_name' => 'Retail Credit Team'],
            ['bank_code' => '03', 'branch_code' => '354', 'branch_name' => 'Credit Operations'],
            ['bank_code' => '03', 'branch_code' => '400', 'branch_name' => 'Head office'],
            ['bank_code' => '03', 'branch_code' => '149', 'branch_name' => 'ABSA BBS Mall'],
            ['bank_code' => '03', 'branch_code' => '152', 'branch_name' => 'Absa Imara Mall'],
            ['bank_code' => '03', 'branch_code' => '128', 'branch_name' => 'Bamburi Location'],
            ['bank_code' => '03', 'branch_code' => '130', 'branch_name' => 'Harambee Ave - Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '132', 'branch_name' => 'Kitale Location'],
            ['bank_code' => '03', 'branch_code' => '139', 'branch_name' => 'Nyahururu Location'],
            ['bank_code' => '03', 'branch_code' => '144', 'branch_name' => 'Treasury Operations'],
            ['bank_code' => '03', 'branch_code' => '145', 'branch_name' => 'Moi Avenue Mombasa - Premier Life Centre'],
            ['bank_code' => '03', 'branch_code' => '151', 'branch_name' => 'Cash Monitoring Unit'],
            ['bank_code' => '03', 'branch_code' => '049', 'branch_name' => 'Lavington Location'],
            ['bank_code' => '03', 'branch_code' => '050', 'branch_name' => 'Tala'],
            ['bank_code' => '03', 'branch_code' => '051', 'branch_name' => 'Homa Bay Location'],
            ['bank_code' => '03', 'branch_code' => '052', 'branch_name' => 'Ongata Rongai Location'],
            ['bank_code' => '03', 'branch_code' => '053', 'branch_name' => 'Othaya Location'],
            ['bank_code' => '03', 'branch_code' => '054', 'branch_name' => 'Voi Location'],
            ['bank_code' => '03', 'branch_code' => '055', 'branch_name' => 'Muthaiga Location'],
            ['bank_code' => '03', 'branch_code' => '056', 'branch_name' => 'Barclays Advisory And Reg. Services'],
            ['bank_code' => '03', 'branch_code' => '057', 'branch_name' => 'Githunguri Location'],
            ['bank_code' => '03', 'branch_code' => '058', 'branch_name' => 'Webuye Location'],
            ['bank_code' => '03', 'branch_code' => '059', 'branch_name' => 'Kasarani Location'],
            ['bank_code' => '03', 'branch_code' => '060', 'branch_name' => 'Chuka Location'],
            ['bank_code' => '03', 'branch_code' => '061', 'branch_name' => 'Nakumatt-westgate Location'],
            ['bank_code' => '03', 'branch_code' => '062', 'branch_name' => 'Kabarnet Location'],
            ['bank_code' => '03', 'branch_code' => '063', 'branch_name' => 'Kerugoya Location'],
            ['bank_code' => '03', 'branch_code' => '064', 'branch_name' => 'Taveta Location'],
            ['bank_code' => '05', 'branch_code' => '000', 'branch_name' => 'Kenyatta Avenue , Nairobi'],
            ['bank_code' => '05', 'branch_code' => '001', 'branch_name' => 'Nkrumah Road , Mombasa'],
            ['bank_code' => '05', 'branch_code' => '002', 'branch_name' => 'Industrial Area'],
            ['bank_code' => '05', 'branch_code' => '003', 'branch_name' => 'Westlands'],
            ['bank_code' => '05', 'branch_code' => '005', 'branch_name' => 'Eldoret'],
            ['bank_code' => '06', 'branch_code' => '007', 'branch_name' => 'Industrial Area'],
            ['bank_code' => '06', 'branch_code' => '008', 'branch_name' => 'Eldoret'],
            ['bank_code' => '06', 'branch_code' => '009', 'branch_name' => 'Nakuru'],
            ['bank_code' => '06', 'branch_code' => '010', 'branch_name' => 'Kakamega'],
            ['bank_code' => '06', 'branch_code' => '011', 'branch_name' => 'Nyali Mombasa'],
            ['bank_code' => '06', 'branch_code' => '012', 'branch_name' => 'Meru'],
            ['bank_code' => '06', 'branch_code' => '015', 'branch_name' => 'Diamond Plaza'],
            ['bank_code' => '06', 'branch_code' => '016', 'branch_name' => 'Mombasa Road'],
            ['bank_code' => '06', 'branch_code' => '000', 'branch_name' => 'Nairobi Main'],
            ['bank_code' => '06', 'branch_code' => '002', 'branch_name' => 'Digo Road, Mombasa'],
            ['bank_code' => '06', 'branch_code' => '004', 'branch_name' => 'Thika'],
            ['bank_code' => '06', 'branch_code' => '005', 'branch_name' => 'Kisumu'],
            ['bank_code' => '06', 'branch_code' => '006', 'branch_name' => 'Sarit Centre'],
            ['bank_code' => '06', 'branch_code' => '017', 'branch_name' => 'Muthithi road'],
            ['bank_code' => '07', 'branch_code' => '235', 'branch_name' => 'Nyahururu Location'],
            ['bank_code' => '07', 'branch_code' => '204', 'branch_name' => 'Sarit Centre Location'],
            ['bank_code' => '07', 'branch_code' => '000', 'branch_name' => 'Head Office'],
            ['bank_code' => '07', 'branch_code' => '001', 'branch_name' => 'Upper Hill'],
            ['bank_code' => '07', 'branch_code' => '002', 'branch_name' => 'Wabera Street'],
            ['bank_code' => '07', 'branch_code' => '003', 'branch_name' => 'Mama Ngina'],
            ['bank_code' => '07', 'branch_code' => '004', 'branch_name' => 'Westlands Location'],
            ['bank_code' => '07', 'branch_code' => '232', 'branch_name' => 'Kitui Location'],
            ['bank_code' => '07', 'branch_code' => '104', 'branch_name' => 'Head Office-Fargo'],
            ['bank_code' => '07', 'branch_code' => '108', 'branch_name' => 'City Mall Location'],
            ['bank_code' => '07', 'branch_code' => '109', 'branch_name' => 'Nkrumah Road'],
            ['bank_code' => '07', 'branch_code' => '227', 'branch_name' => 'RUAKA BRANCH'],
            ['bank_code' => '07', 'branch_code' => '115', 'branch_name' => 'Galleria (Bomas)'],
            ['bank_code' => '07', 'branch_code' => '116', 'branch_name' => 'Eldoret'],
            ['bank_code' => '07', 'branch_code' => '117', 'branch_name' => 'Village Market'],
            ['bank_code' => '07', 'branch_code' => '236', 'branch_name' => 'Tatu City Location'],
            ['bank_code' => '07', 'branch_code' => '233', 'branch_name' => 'Kerugoya Location'],
            ['bank_code' => '07', 'branch_code' => '231', 'branch_name' => 'Githunguri'],
            ['bank_code' => '07', 'branch_code' => '230', 'branch_name' => 'Limuru'],
            ['bank_code' => '07', 'branch_code' => '234', 'branch_name' => 'Kawangware'],
            ['bank_code' => '07', 'branch_code' => '229', 'branch_name' => 'Homa Bay'],
            ['bank_code' => '07', 'branch_code' => '225', 'branch_name' => 'Wote Location'],
            ['bank_code' => '07', 'branch_code' => '228', 'branch_name' => 'Kapsabet Location'],
            ['bank_code' => '07', 'branch_code' => '219', 'branch_name' => 'Busia'],
            ['bank_code' => '07', 'branch_code' => '223', 'branch_name' => 'Kenol Town'],
            ['bank_code' => '07', 'branch_code' => '222', 'branch_name' => 'Utawala Nairobi'],
            ['bank_code' => '07', 'branch_code' => '221', 'branch_name' => 'Eastleigh Nairobi'],
            ['bank_code' => '07', 'branch_code' => '33', 'branch_name' => 'River Road'],
            ['bank_code' => '07', 'branch_code' => '218', 'branch_name' => 'Muranga'],
            ['bank_code' => '07', 'branch_code' => '224', 'branch_name' => 'Kahawa Sukari'],
            ['bank_code' => '07', 'branch_code' => '220', 'branch_name' => 'Chwele'],
            ['bank_code' => '07', 'branch_code' => '226', 'branch_name' => 'Migori Location'],
            ['bank_code' => '07', 'branch_code' => '131', 'branch_name' => 'Kisii'],
            ['bank_code' => '07', 'branch_code' => '132', 'branch_name' => 'KMA Centre'],
            ['bank_code' => '07', 'branch_code' => '133', 'branch_name' => 'Buru Buru'],
            ['bank_code' => '07', 'branch_code' => '134', 'branch_name' => 'CPA Centre, Ruaraka'],
            ['bank_code' => '07', 'branch_code' => '135', 'branch_name' => 'Rongai'],
            ['bank_code' => '07', 'branch_code' => '141', 'branch_name' => 'Rosslyn Riviera'],
            ['bank_code' => '07', 'branch_code' => '142', 'branch_name' => 'Ciata Mall'],
            ['bank_code' => '07', 'branch_code' => '143', 'branch_name' => 'Parklands'],
            ['bank_code' => '07', 'branch_code' => '144', 'branch_name' => 'Nanyuki'],
            ['bank_code' => '07', 'branch_code' => '145', 'branch_name' => 'Malindi'],
            ['bank_code' => '07', 'branch_code' => '005', 'branch_name' => 'Industrial Area'],
            ['bank_code' => '07', 'branch_code' => '006', 'branch_name' => 'Mamlaka'],
            ['bank_code' => '07', 'branch_code' => '007', 'branch_name' => 'Village Market'],
            ['bank_code' => '07', 'branch_code' => '008', 'branch_name' => 'Cargo Centre'],
            ['bank_code' => '07', 'branch_code' => '009', 'branch_name' => 'Park Side'],
            ['bank_code' => '07', 'branch_code' => '026', 'branch_name' => 'Eldoret'],
            ['bank_code' => '07', 'branch_code' => '027', 'branch_name' => 'Kisumu'],
            ['bank_code' => '07', 'branch_code' => '028', 'branch_name' => 'Thika'],
            ['bank_code' => '07', 'branch_code' => '029', 'branch_name' => 'Nanyuki'],
            ['bank_code' => '07', 'branch_code' => '030', 'branch_name' => 'Yaya Centre'],
            ['bank_code' => '07', 'branch_code' => '031', 'branch_name' => 'Lavington'],
            ['bank_code' => '07', 'branch_code' => '032', 'branch_name' => 'Machakos'],
            ['bank_code' => '07', 'branch_code' => '016', 'branch_name' => 'Galleria Mall'],
            ['bank_code' => '07', 'branch_code' => '017', 'branch_name' => 'Junction'],
            ['bank_code' => '07', 'branch_code' => '018', 'branch_name' => 'Thika Road Mall'],
            ['bank_code' => '07', 'branch_code' => '019', 'branch_name' => 'Greenspan Mall'],
            ['bank_code' => '07', 'branch_code' => '020', 'branch_name' => 'Moi Avenue Mombasa'],
            ['bank_code' => '07', 'branch_code' => '021', 'branch_name' => 'Meru'],
            ['bank_code' => '07', 'branch_code' => '022', 'branch_name' => 'Nakuru'],
            ['bank_code' => '07', 'branch_code' => '023', 'branch_name' => 'Nyali'],
            ['bank_code' => '07', 'branch_code' => '024', 'branch_name' => 'Diani'],
            ['bank_code' => '07', 'branch_code' => '025', 'branch_name' => 'Changamwe'],
            ['bank_code' => '07', 'branch_code' => '209', 'branch_name' => 'Mwembe Tayari'],
            ['bank_code' => '07', 'branch_code' => '208', 'branch_name' => 'Ruiru Eastern Bypass'],
            ['bank_code' => '07', 'branch_code' => '206', 'branch_name' => 'Nyeri'],
            ['bank_code' => '07', 'branch_code' => '207', 'branch_name' => 'Karatina'],
            ['bank_code' => '07', 'branch_code' => '210', 'branch_name' => 'Kakamega'],
            ['bank_code' => '07', 'branch_code' => '033', 'branch_name' => 'River Road'],
            ['bank_code' => '07', 'branch_code' => '034', 'branch_name' => 'Karen Hub'],
            ['bank_code' => '07', 'branch_code' => '211', 'branch_name' => 'Kericho'],
            ['bank_code' => '07', 'branch_code' => '213', 'branch_name' => 'Bungoma'],
            ['bank_code' => '07', 'branch_code' => '212', 'branch_name' => 'Embu'],
            ['bank_code' => '07', 'branch_code' => '216', 'branch_name' => 'Gikomba'],
            ['bank_code' => '07', 'branch_code' => '214', 'branch_name' => 'Ngong'],
            ['bank_code' => '07', 'branch_code' => '215', 'branch_name' => 'Kiambu'],
            ['bank_code' => '07', 'branch_code' => '217', 'branch_name' => 'Naivasha'],
            ['bank_code' => '07', 'branch_code' => '035', 'branch_name' => 'Garden City'],
            ['bank_code' => '07', 'branch_code' => '036', 'branch_name' => 'Two Rivers Mall'],
            ['bank_code' => '07', 'branch_code' => '101', 'branch_name' => 'City Centre'],
            ['bank_code' => '07', 'branch_code' => '102', 'branch_name' => 'NIC House'],
            ['bank_code' => '07', 'branch_code' => '103', 'branch_name' => 'Harbour House'],
            ['bank_code' => '07', 'branch_code' => '105', 'branch_name' => 'The Mall Location, Westlands'],
            ['bank_code' => '07', 'branch_code' => '106', 'branch_name' => 'The Junction Br.'],
            ['bank_code' => '07', 'branch_code' => '107', 'branch_name' => 'Nakuru Tower One Location'],
            ['bank_code' => '07', 'branch_code' => '110', 'branch_name' => 'Harambee'],
            ['bank_code' => '07', 'branch_code' => '111', 'branch_name' => 'Prestige-Ngong Road'],
            ['bank_code' => '07', 'branch_code' => '112', 'branch_name' => 'One Kentons Square Location'],
            ['bank_code' => '07', 'branch_code' => '113', 'branch_name' => 'Thika'],
            ['bank_code' => '07', 'branch_code' => '114', 'branch_name' => 'Meru'],
            ['bank_code' => '07', 'branch_code' => '118', 'branch_name' => 'Sameer Park'],
            ['bank_code' => '07', 'branch_code' => '119', 'branch_name' => 'Karen'],
            ['bank_code' => '07', 'branch_code' => '121', 'branch_name' => 'Taj Mall'],
            ['bank_code' => '07', 'branch_code' => '122', 'branch_name' => 'ABC'],
            ['bank_code' => '07', 'branch_code' => '123', 'branch_name' => 'Thika Road Mall'],
            ['bank_code' => '07', 'branch_code' => '124', 'branch_name' => 'Changamwe Location'],
            ['bank_code' => '07', 'branch_code' => '125', 'branch_name' => 'Kenyatta Avenue'],
            ['bank_code' => '07', 'branch_code' => '126', 'branch_name' => 'Riverside'],
            ['bank_code' => '07', 'branch_code' => '127', 'branch_name' => 'Machakos'],
            ['bank_code' => '07', 'branch_code' => '128', 'branch_name' => 'Lunga Lunga Square'],
            ['bank_code' => '07', 'branch_code' => '129', 'branch_name' => 'Kilimani'],
            ['bank_code' => '07', 'branch_code' => '130', 'branch_name' => 'Kitengela'],
            ['bank_code' => '07', 'branch_code' => '146', 'branch_name' => 'Kilifi'],
            ['bank_code' => '07', 'branch_code' => '147', 'branch_name' => 'Watamu'],
            ['bank_code' => '07', 'branch_code' => '148', 'branch_name' => 'Ukunda Location'],
            ['bank_code' => '07', 'branch_code' => '149', 'branch_name' => 'Kitale'],
            ['bank_code' => '07', 'branch_code' => '200', 'branch_name' => 'Narok Location'],
            ['bank_code' => '07', 'branch_code' => '201', 'branch_name' => 'Lavington Location'],
            ['bank_code' => '07', 'branch_code' => '500', 'branch_name' => 'Head Office'],
            ['bank_code' => '07', 'branch_code' => '501', 'branch_name' => 'Head Office'],
            ['bank_code' => '07', 'branch_code' => '502', 'branch_name' => 'Head Office'],
            ['bank_code' => '07', 'branch_code' => '503', 'branch_name' => 'Head Office'],
            ['bank_code' => '07', 'branch_code' => '600', 'branch_name' => 'Head Office'],
            ['bank_code' => '09', 'branch_code' => '006', 'branch_name' => 'Nakuru Centre'],
            ['bank_code' => '09', 'branch_code' => '000', 'branch_name' => 'Head Office'],
            ['bank_code' => '09', 'branch_code' => '001', 'branch_name' => 'Head Office'],
            ['bank_code' => '09', 'branch_code' => '008', 'branch_name' => 'Kisii Centre'],
            ['bank_code' => '09', 'branch_code' => '003', 'branch_name' => 'Kisumu'],
            ['bank_code' => '09', 'branch_code' => '004', 'branch_name' => 'Eldoret'],
            ['bank_code' => '09', 'branch_code' => '002', 'branch_name' => 'Mombasa'],
            ['bank_code' => '10', 'branch_code' => '025', 'branch_name' => 'Village Market'],
            ['bank_code' => '10', 'branch_code' => '026', 'branch_name' => 'Kitale'],
            ['bank_code' => '10', 'branch_code' => '027', 'branch_name' => 'Baba Dogo'],
            ['bank_code' => '10', 'branch_code' => '019', 'branch_name' => 'Thika'],
            ['bank_code' => '10', 'branch_code' => '020', 'branch_name' => 'Garden City'],
            ['bank_code' => '10', 'branch_code' => '021', 'branch_name' => 'Two Rivers'],
            ['bank_code' => '10', 'branch_code' => '023', 'branch_name' => 'Meru'],
            ['bank_code' => '10', 'branch_code' => '024', 'branch_name' => 'Lavington Location'],
            ['bank_code' => '10', 'branch_code' => '022', 'branch_name' => 'UAP Towers'],
            ['bank_code' => '10', 'branch_code' => '000', 'branch_name' => 'H/o Riverside'],
            ['bank_code' => '10', 'branch_code' => '001', 'branch_name' => 'Kenindia'],
            ['bank_code' => '10', 'branch_code' => '002', 'branch_name' => 'Biashara'],
            ['bank_code' => '10', 'branch_code' => '003', 'branch_name' => 'Mombasa'],
            ['bank_code' => '10', 'branch_code' => '004', 'branch_name' => 'Westlands'],
            ['bank_code' => '10', 'branch_code' => '005', 'branch_name' => 'Industrial Area'],
            ['bank_code' => '10', 'branch_code' => '006', 'branch_name' => 'Kisumu'],
            ['bank_code' => '10', 'branch_code' => '007', 'branch_name' => 'Parklands'],
            ['bank_code' => '10', 'branch_code' => '008', 'branch_name' => 'Riverside Drive'],
            ['bank_code' => '10', 'branch_code' => '009', 'branch_name' => 'Card Centre'],
            ['bank_code' => '10', 'branch_code' => '010', 'branch_name' => 'Hurlingham'],
            ['bank_code' => '10', 'branch_code' => '011', 'branch_name' => 'Capital Centre'],
            ['bank_code' => '10', 'branch_code' => '012', 'branch_name' => 'Nyali'],
            ['bank_code' => '10', 'branch_code' => '014', 'branch_name' => 'Kamukunji'],
            ['bank_code' => '10', 'branch_code' => '015', 'branch_name' => 'Eldoret'],
            ['bank_code' => '10', 'branch_code' => '016', 'branch_name' => 'Karen'],
            ['bank_code' => '10', 'branch_code' => '017', 'branch_name' => 'Nakuru'],
            ['bank_code' => '11', 'branch_code' => '083', 'branch_name' => 'Keroka'],
            ['bank_code' => '11', 'branch_code' => '084', 'branch_name' => 'Gilgil'],
            ['bank_code' => '11', 'branch_code' => '085', 'branch_name' => 'Tom Mboya'],
            ['bank_code' => '11', 'branch_code' => '086', 'branch_name' => 'Likoni'],
            ['bank_code' => '11', 'branch_code' => '087', 'branch_name' => 'Donholm'],
            ['bank_code' => '11', 'branch_code' => '088', 'branch_name' => 'Mwingi'],
            ['bank_code' => '11', 'branch_code' => '089', 'branch_name' => 'Ruaka'],
            ['bank_code' => '11', 'branch_code' => '090', 'branch_name' => 'Webuye'],
            ['bank_code' => '11', 'branch_code' => '094', 'branch_name' => 'Sacco Clearing Unit'],
            ['bank_code' => '11', 'branch_code' => '097', 'branch_name' => 'Clearing Centre'],
            ['bank_code' => '11', 'branch_code' => '100', 'branch_name' => 'Ndhiwa'],
            ['bank_code' => '11', 'branch_code' => '101', 'branch_name' => 'Oyugis'],
            ['bank_code' => '11', 'branch_code' => '102', 'branch_name' => 'Isiolo'],
            ['bank_code' => '11', 'branch_code' => '103', 'branch_name' => 'Uganda Road Eldoret'],
            ['bank_code' => '11', 'branch_code' => '104', 'branch_name' => 'Changamwe'],
            ['bank_code' => '11', 'branch_code' => '105', 'branch_name' => 'Kondele'],
            ['bank_code' => '11', 'branch_code' => '106', 'branch_name' => 'Githurai Kimbo'],
            ['bank_code' => '11', 'branch_code' => '107', 'branch_name' => 'Mlolongo'],
            ['bank_code' => '11', 'branch_code' => '108', 'branch_name' => 'Kilifi'],
            ['bank_code' => '11', 'branch_code' => '109', 'branch_name' => 'Ol Kalau'],
            ['bank_code' => '11', 'branch_code' => '110', 'branch_name' => 'Mbale'],
            ['bank_code' => '11', 'branch_code' => '111', 'branch_name' => 'Kimilili'],
            ['bank_code' => '11', 'branch_code' => '035', 'branch_name' => 'Stima Plaza'],
            ['bank_code' => '11', 'branch_code' => '170', 'branch_name' => 'Kamulu Location'],
            ['bank_code' => '11', 'branch_code' => '156', 'branch_name' => 'Ridgeways Mall'],
            ['bank_code' => '11', 'branch_code' => '157', 'branch_name' => 'Two Rivers Mall'],
            ['bank_code' => '11', 'branch_code' => '158', 'branch_name' => 'JKIA'],
            ['bank_code' => '11', 'branch_code' => '154', 'branch_name' => 'Gikomba Area 42'],
            ['bank_code' => '11', 'branch_code' => '166', 'branch_name' => 'Kapenguria Sub - Location'],
            ['bank_code' => '11', 'branch_code' => '162', 'branch_name' => 'Litein'],
            ['bank_code' => '11', 'branch_code' => '161', 'branch_name' => 'Kilimani'],
            ['bank_code' => '11', 'branch_code' => '159', 'branch_name' => 'Emali'],
            ['bank_code' => '11', 'branch_code' => '163', 'branch_name' => 'Thika Makongeni'],
            ['bank_code' => '11', 'branch_code' => '160', 'branch_name' => 'Kangema'],
            ['bank_code' => '11', 'branch_code' => '155', 'branch_name' => 'Utawala'],
            ['bank_code' => '11', 'branch_code' => '020', 'branch_name' => 'Eastleigh'],
            ['bank_code' => '11', 'branch_code' => '021', 'branch_name' => 'Kiambu'],
            ['bank_code' => '11', 'branch_code' => '022', 'branch_name' => 'Homa Bay'],
            ['bank_code' => '11', 'branch_code' => '023', 'branch_name' => 'Embu'],
            ['bank_code' => '11', 'branch_code' => '024', 'branch_name' => 'Kericho'],
            ['bank_code' => '11', 'branch_code' => '025', 'branch_name' => 'Bungoma'],
            ['bank_code' => '11', 'branch_code' => '026', 'branch_name' => 'Muranga'],
            ['bank_code' => '11', 'branch_code' => '027', 'branch_name' => 'Kayole'],
        ];

        // Insert locations into the database
        foreach ($locations as $location) {
            if (isset($banks[$location['bank_code']])) {
                // Check if branch already exists
                $existingBranch = DB::table('bank_branches')
                    ->where('bank_id', $banks[$location['bank_code']])
                    ->where('branch_code', $location['branch_code'])
                    ->first();

                if (!$existingBranch) {
                    DB::table('bank_branches')->insert([
                        'bank_id' => $banks[$location['bank_code']],
                        'branch_name' => $location['branch_name'],
                        'branch_code' => $location['branch_code'],
                        'status' => 1, // Active by default
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }
    }
}
