<?php

namespace App\Lib\Enumerations;

class Nationality
{
    public const AFGHANISTAN = 1;
    public const ALBANIA = 2;
    public const ALGERIA = 3;
    public const ANDORRA = 4;
    public const ANGOLA = 5;
    public const ANTIGUA_AND_BARBUDA = 6;
    public const ARGENTINA = 7;
    public const ARMENIA = 8;
    public const AUSTRALIA = 9;
    public const AUSTRIA = 10;
    public const AZERBAIJAN = 11;
    public const BAHAMAS = 12;
    public const BAHRAIN = 13;
    public const BANGLADESH = 14;
    public const BARBADOS = 15;
    public const BELARUS = 16;
    public const BELGIUM = 17;
    public const BELIZE = 18;
    public const BENIN = 19;
    public const BHUTAN = 20;
    public const BOLIVIA = 21;
    public const BOSNIA_AND_HERZEGOVINA = 22;
    public const BOTSWANA = 23;
    public const BRAZIL = 24;
    public const BRUNEI = 25;
    public const BULGARIA = 26;
    public const BURKINA_FASO = 27;
    public const BURUNDI = 28;
    public const CABO_VERDE = 29;
    public const CAMBODIA = 30;
    public const CAMEROON = 31;
    public const CANADA = 32;
    public const CENTRAL_AFRICAN_REPUBLIC = 33;
    public const CHAD = 34;
    public const CHILE = 35;
    public const CHINA = 36;
    public const COLOMBIA = 37;
    public const COMOROS = 38;
    public const CONGO_REPUBLIC = 39;
    public const CONGO_DEMOCRATIC_REPUBLIC = 40;
    public const COSTA_RICA = 41;
    public const CROATIA = 42;
    public const CUBA = 43;
    public const CYPRUS = 44;
    public const CZECH_REPUBLIC = 45;
    public const DENMARK = 46;
    public const DJIBOUTI = 47;
    public const DOMINICA = 48;
    public const DOMINICAN_REPUBLIC = 49;
    public const ECUADOR = 50;
    public const EGYPT = 51;
    public const EL_SALVADOR = 52;
    public const EQUATORIAL_GUINEA = 53;
    public const ERITREA = 54;
    public const ESTONIA = 55;
    public const ESWATINI = 56;
    public const ETHIOPIA = 57;
    public const FIJI = 58;
    public const FINLAND = 59;
    public const FRANCE = 60;
    public const GABON = 61;
    public const GAMBIA = 62;
    public const GEORGIA = 63;
    public const GERMANY = 64;
    public const GHANA = 65;
    public const GREECE = 66;
    public const GRENADA = 67;
    public const GUATEMALA = 68;
    public const GUINEA = 69;
    public const GUINEA_BISSAU = 70;
    public const GUYANA = 71;
    public const HAITI = 72;
    public const HONDURAS = 73;
    public const HUNGARY = 74;
    public const ICELAND = 75;
    public const INDIA = 76;
    public const INDONESIA = 77;
    public const IRAN = 78;
    public const IRAQ = 79;
    public const IRELAND = 80;
    public const ISRAEL = 81;
    public const ITALY = 82;
    public const IVORY_COAST = 83;
    public const JAMAICA = 84;
    public const JAPAN = 85;
    public const JORDAN = 86;
    public const KAZAKHSTAN = 87;
    public const KENYA = 88;
    public const KIRIBATI = 89;
    public const KOREA_NORTH = 90;
    public const KOREA_SOUTH = 91;
    public const KUWAIT = 92;
    public const KYRGYZSTAN = 93;
    public const LAOS = 94;
    public const LATVIA = 95;
    public const LEBANON = 96;
    public const LESOTHO = 97;
    public const LIBERIA = 98;
    public const LIBYA = 99;
    public const LIECHTENSTEIN = 100;
    public const LITHUANIA = 101;
    public const LUXEMBOURG = 102;
    public const MADAGASCAR = 103;
    public const MALAWI = 104;
    public const MALAYSIA = 105;
    public const MALDIVES = 106;
    public const MALI = 107;
    public const MALTA = 108;
    public const MARSHALL_ISLANDS = 109;
    public const MAURITANIA = 110;
    public const MAURITIUS = 111;
    public const MEXICO = 112;
    public const MICRONESIA = 113;
    public const MOLDOVA = 114;
    public const MONACO = 115;
    public const MONGOLIA = 116;
    public const MONTENEGRO = 117;
    public const MOROCCO = 118;
    public const MOZAMBIQUE = 119;
    public const MYANMAR = 120;
    public const NAMIBIA = 121;
    public const NAURU = 122;
    public const NEPAL = 123;
    public const NETHERLANDS = 124;
    public const NEW_ZEALAND = 125;
    public const NICARAGUA = 126;
    public const NIGER = 127;
    public const NIGERIA = 128;
    public const NORTH_MACEDONIA = 129;
    public const NORWAY = 130;
    public const OMAN = 131;
    public const PAKISTAN = 132;
    public const PALAU = 133;
    public const PANAMA = 134;
    public const PAPUA_NEW_GUINEA = 135;
    public const PARAGUAY = 136;
    public const PERU = 137;
    public const PHILIPPINES = 138;
    public const POLAND = 139;
    public const PORTUGAL = 140;
    public const QATAR = 141;
    public const ROMANIA = 142;
    public const RUSSIA = 143;
    public const RWANDA = 144;
    public const SAINT_KITTS_AND_NEVIS = 145;
    public const SAINT_LUCIA = 146;
    public const SAINT_VINCENT_AND_THE_GRENADINES = 147;
    public const SAMOA = 148;
    public const SAN_MARINO = 149;
    public const SAO_TOME_AND_PRINCIPE = 150;
    public const SAUDI_ARABIA = 151;
    public const SENEGAL = 152;
    public const SERBIA = 153;
    public const SEYCHELLES = 154;
    public const SIERRA_LEONE = 155;
    public const SINGAPORE = 156;
    public const SLOVAKIA = 157;
    public const SLOVENIA = 158;
    public const SOLOMON_ISLANDS = 159;
    public const SOMALIA = 160;
    public const SOUTH_AFRICA = 161;
    public const SOUTH_SUDAN = 162;
    public const SPAIN = 163;
    public const SRI_LANKA = 164;
    public const SUDAN = 165;
    public const SURINAME = 166;
    public const SWEDEN = 167;
    public const SWITZERLAND = 168;
    public const SYRIA = 169;
    public const TAIWAN = 170;
    public const TAJIKISTAN = 171;
    public const TANZANIA = 172;
    public const THAILAND = 173;
    public const TIMOR_LESTE = 174;
    public const TOGO = 175;
    public const TONGA = 176;
    public const TRINIDAD_AND_TOBAGO = 177;
    public const TUNISIA = 178;
    public const TURKEY = 179;
    public const TURKMENISTAN = 180;
    public const TUVALU = 181;
    public const UGANDA = 182;
    public const UKRAINE = 183;
    public const UNITED_ARAB_EMIRATES = 184;
    public const UNITED_KINGDOM = 185;
    public const UNITED_STATES = 186;
    public const URUGUAY = 187;
    public const UZBEKISTAN = 188;
    public const VANUATU = 189;
    public const VATICAN_CITY = 190;
    public const VENEZUELA = 191;
    public const VIETNAM = 192;
    public const YEMEN = 193;
    public const ZAMBIA = 194;
    public const ZIMBABWE = 195;
    public const OTHER = 196;

    public static function toArray(): array
    {
        return [
            self::AFGHANISTAN => 'AFGHANISTAN',
            self::ALBANIA => 'ALBANIA',
            self::ALGERIA => 'ALGERIA',
            self::ANDORRA => 'ANDORRA',
            self::ANGOLA => 'ANGOLA',
            self::ANTIGUA_AND_BARBUDA => 'ANTIGUA AND BARBUDA',
            self::ARGENTINA => 'ARGENTINA',
            self::ARMENIA => 'ARMENIA',
            self::AUSTRALIA => 'AUSTRALIA',
            self::AUSTRIA => 'AUSTRIA',
            self::AZERBAIJAN => 'AZERBAIJAN',
            self::BAHAMAS => 'BAHAMAS',
            self::BAHRAIN => 'BAHRAIN',
            self::BANGLADESH => 'BANGLADESH',
            self::BARBADOS => 'BARBADOS',
            self::BELARUS => 'BELARUS',
            self::BELGIUM => 'BELGIUM',
            self::BELIZE => 'BELIZE',
            self::BENIN => 'BENIN',
            self::BHUTAN => 'BHUTAN',
            self::BOLIVIA => 'BOLIVIA',
            self::BOSNIA_AND_HERZEGOVINA => 'BOSNIA AND HERZEGOVINA',
            self::BOTSWANA => 'BOTSWANA',
            self::BRAZIL => 'BRAZIL',
            self::BRUNEI => 'BRUNEI',
            self::BULGARIA => 'BULGARIA',
            self::BURKINA_FASO => 'BURKINA FASO',
            self::BURUNDI => 'BURUNDI',
            self::CABO_VERDE => 'CABO VERDE',
            self::CAMBODIA => 'CAMBODIA',
            self::CAMEROON => 'CAMEROON',
            self::CANADA => 'CANADA',
            self::CENTRAL_AFRICAN_REPUBLIC => 'CENTRAL AFRICAN REPUBLIC',
            self::CHAD => 'CHAD',
            self::CHILE => 'CHILE',
            self::CHINA => 'CHINA',
            self::COLOMBIA => 'COLOMBIA',
            self::COMOROS => 'COMOROS',
            self::CONGO_REPUBLIC => 'CONGO, REPUBLIC OF THE',
            self::CONGO_DEMOCRATIC_REPUBLIC => 'CONGO, DEMOCRATIC REPUBLIC OF THE',
            self::COSTA_RICA => 'COSTA RICA',
            self::CROATIA => 'CROATIA',
            self::CUBA => 'CUBA',
            self::CYPRUS => 'CYPRUS',
            self::CZECH_REPUBLIC => 'CZECH REPUBLIC',
            self::DENMARK => 'DENMARK',
            self::DJIBOUTI => 'DJIBOUTI',
            self::DOMINICA => 'DOMINICA',
            self::DOMINICAN_REPUBLIC => 'DOMINICAN REPUBLIC',
            self::ECUADOR => 'ECUADOR',
            self::EGYPT => 'EGYPT',
            self::EL_SALVADOR => 'EL SALVADOR',
            self::EQUATORIAL_GUINEA => 'EQUATORIAL GUINEA',
            self::ERITREA => 'ERITREA',
            self::ESTONIA => 'ESTONIA',
            self::ESWATINI => 'ESWATINI',
            self::ETHIOPIA => 'ETHIOPIA',
            self::FIJI => 'FIJI',
            self::FINLAND => 'FINLAND',
            self::FRANCE => 'FRANCE',
            self::GABON => 'GABON',
            self::GAMBIA => 'GAMBIA',
            self::GEORGIA => 'GEORGIA',
            self::GERMANY => 'GERMANY',
            self::GHANA => 'GHANA',
            self::GREECE => 'GREECE',
            self::GRENADA => 'GRENADA',
            self::GUATEMALA => 'GUATEMALA',
            self::GUINEA => 'GUINEA',
            self::GUINEA_BISSAU => 'GUINEA-BISSAU',
            self::GUYANA => 'GUYANA',
            self::HAITI => 'HAITI',
            self::HONDURAS => 'HONDURAS',
            self::HUNGARY => 'HUNGARY',
            self::ICELAND => 'ICELAND',
            self::INDIA => 'INDIA',
            self::INDONESIA => 'INDONESIA',
            self::IRAN => 'IRAN',
            self::IRAQ => 'IRAQ',
            self::IRELAND => 'IRELAND',
            self::ISRAEL => 'ISRAEL',
            self::ITALY => 'ITALY',
            self::IVORY_COAST => 'IVORY COAST',
            self::JAMAICA => 'JAMAICA',
            self::JAPAN => 'JAPAN',
            self::JORDAN => 'JORDAN',
            self::KAZAKHSTAN => 'KAZAKHSTAN',
            self::KENYA => 'KENYA',
            self::KIRIBATI => 'KIRIBATI',
            self::KOREA_NORTH => 'KOREA, NORTH',
            self::KOREA_SOUTH => 'KOREA, SOUTH',
            self::KUWAIT => 'KUWAIT',
            self::KYRGYZSTAN => 'KYRGYZSTAN',
            self::LAOS => 'LAOS',
            self::LATVIA => 'LATVIA',
            self::LEBANON => 'LEBANON',
            self::LESOTHO => 'LESOTHO',
            self::LIBERIA => 'LIBERIA',
            self::LIBYA => 'LIBYA',
            self::LIECHTENSTEIN => 'LIECHTENSTEIN',
            self::LITHUANIA => 'LITHUANIA',
            self::LUXEMBOURG => 'LUXEMBOURG',
            self::MADAGASCAR => 'MADAGASCAR',
            self::MALAWI => 'MALAWI',
            self::MALAYSIA => 'MALAYSIA',
            self::MALDIVES => 'MALDIVES',
            self::MALI => 'MALI',
            self::MALTA => 'MALTA',
            self::MARSHALL_ISLANDS => 'MARSHALL ISLANDS',
            self::MAURITANIA => 'MAURITANIA',
            self::MAURITIUS => 'MAURITIUS',
            self::MEXICO => 'MEXICO',
            self::MICRONESIA => 'MICRONESIA',
            self::MOLDOVA => 'MOLDOVA',
            self::MONACO => 'MONACO',
            self::MONGOLIA => 'MONGOLIA',
            self::MONTENEGRO => 'MONTENEGRO',
            self::MOROCCO => 'MOROCCO',
            self::MOZAMBIQUE => 'MOZAMBIQUE',
            self::MYANMAR => 'MYANMAR',
            self::NAMIBIA => 'NAMIBIA',
            self::NAURU => 'NAURU',
            self::NEPAL => 'NEPAL',
            self::NETHERLANDS => 'NETHERLANDS',
            self::NEW_ZEALAND => 'NEW ZEALAND',
            self::NICARAGUA => 'NICARAGUA',
            self::NIGER => 'NIGER',
            self::NIGERIA => 'NIGERIA',
            self::NORTH_MACEDONIA => 'NORTH MACEDONIA',
            self::NORWAY => 'NORWAY',
            self::OMAN => 'OMAN',
            self::PAKISTAN => 'PAKISTAN',
            self::PALAU => 'PALAU',
            self::PANAMA => 'PANAMA',
            self::PAPUA_NEW_GUINEA => 'PAPUA NEW GUINEA',
            self::PARAGUAY => 'PARAGUAY',
            self::PERU => 'PERU',
            self::PHILIPPINES => 'PHILIPPINES',
            self::POLAND => 'POLAND',
            self::PORTUGAL => 'PORTUGAL',
            self::QATAR => 'QATAR',
            self::ROMANIA => 'ROMANIA',
            self::RUSSIA => 'RUSSIA',
            self::RWANDA => 'RWANDA',
            self::SAINT_KITTS_AND_NEVIS => 'SAINT KITTS AND NEVIS',
            self::SAINT_LUCIA => 'SAINT LUCIA',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'SAINT VINCENT AND THE GRENADINES',
            self::SAMOA => 'SAMOA',
            self::SAN_MARINO => 'SAN MARINO',
            self::SAO_TOME_AND_PRINCIPE => 'SAO TOME AND PRINCIPE',
            self::SAUDI_ARABIA => 'SAUDI ARABIA',
            self::SENEGAL => 'SENEGAL',
            self::SERBIA => 'SERBIA',
            self::SEYCHELLES => 'SEYCHELLES',
            self::SIERRA_LEONE => 'SIERRA LEONE',
            self::SINGAPORE => 'SINGAPORE',
            self::SLOVAKIA => 'SLOVAKIA',
            self::SLOVENIA => 'SLOVENIA',
            self::SOLOMON_ISLANDS => 'SOLOMON ISLANDS',
            self::SOMALIA => 'SOMALIA',
            self::SOUTH_AFRICA => 'SOUTH AFRICA',
            self::SOUTH_SUDAN => 'SOUTH SUDAN',
            self::SPAIN => 'SPAIN',
            self::SRI_LANKA => 'SRI LANKA',
            self::SUDAN => 'SUDAN',
            self::SURINAME => 'SURINAME',
            self::SWEDEN => 'SWEDEN',
            self::SWITZERLAND => 'SWITZERLAND',
            self::SYRIA => 'SYRIA',
            self::TAIWAN => 'TAIWAN',
            self::TAJIKISTAN => 'TAJIKISTAN',
            self::TANZANIA => 'TANZANIA',
            self::THAILAND => 'THAILAND',
            self::TIMOR_LESTE => 'TIMOR-LESTE',
            self::TOGO => 'TOGO',
            self::TONGA => 'TONGA',
            self::TRINIDAD_AND_TOBAGO => 'TRINIDAD AND TOBAGO',
            self::TUNISIA => 'TUNISIA',
            self::TURKEY => 'TURKEY',
            self::TURKMENISTAN => 'TURKMENISTAN',
            self::TUVALU => 'TUVALU',
            self::UGANDA => 'UGANDA',
            self::UKRAINE => 'UKRAINE',
            self::UNITED_ARAB_EMIRATES => 'UNITED ARAB EMIRATES',
            self::UNITED_KINGDOM => 'UNITED KINGDOM',
            self::UNITED_STATES => 'UNITED STATES',
            self::URUGUAY => 'URUGUAY',
            self::UZBEKISTAN => 'UZBEKISTAN',
            self::VANUATU => 'VANUATU',
            self::VATICAN_CITY => 'VATICAN CITY',
            self::VENEZUELA => 'VENEZUELA',
            self::VIETNAM => 'VIETNAM',
            self::YEMEN => 'YEMEN',
            self::ZAMBIA => 'ZAMBIA',
            self::ZIMBABWE => 'ZIMBABWE',
            self::OTHER => 'OTHER',
        ];
    }

    public static function getName($value): string
    {
        $countries = self::toArray();
        return $countries[$value] ?? 'Unknown';
    }

    public static function getValue($name)
    {
        $countries = array_flip(self::toArray());
        return $countries[strtoupper($name)] ?? null;
    }
}
